<?php // fill in the blanks with your stuff
$token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
$token_secret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
$consumer_key = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
$consumer_secret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
?>
